name: Deploy to S3 on Merge Request

on:
  push:
    branches:
      - master  # Triggers when a PR is created for master
    paths-ignore:
      - 'README.md'
      - '.git/*'
      - '.github/*'
      - 'styles/common-style.css.map'
      - 'styles/common-style.scss'
      - 'styles/style.css.map'
      - 'styles/style.scss'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete